const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), vm=require('node:vm'), path=require('node:path');
const root=path.resolve(__dirname,'..'); const read=f=>fs.readFileSync(path.join(root,f),'utf8');
function core(){
  let now=0,next=0; const pending=new Map(), voices=[];
  const context={console,localStorage:{getItem:()=>null,setItem(){}},Audio:function(){this.pause=()=>{};this.play=()=>Promise.resolve();voices.push(this);},setTimeout:(fn,delay)=>{pending.set(++next,{fn,at:now+delay});return next;},clearTimeout:id=>pending.delete(id),setInterval:()=>++next,clearInterval(){},CustomEvent:function(){},window:{addEventListener(){},dispatchEvent(){}},document:{addEventListener(){},getElementById:()=>null,documentElement:{classList:{toggle(){}}}}};
  vm.createContext(context);vm.runInContext(read('app-core.js'),context);
  return {app:context.window.Playbox,voices,advance(ms){now+=ms;for(const [id,t] of [...pending])if(t.at<=now){pending.delete(id);t.fn();}}};
}
test('all shipped JavaScript parses',()=>{for(const file of ['index.html','learn.html'])for(const m of read(file).matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);for(const f of ['app-core.js','app-shell.js','catalog.js','houses.js','sw.js'])new vm.Script(read(f));});
test('navigation cancels voice completions and delayed rounds',()=>{const c=core();let fired=0;c.app.audio.play('Yay!',()=>fired++);c.app.session.timeout(()=>fired++,500);const stale=c.voices[0].onended;c.app.session.clear();stale();c.advance(11000);assert.equal(fired,0);});
test('interrupted and muted praise completes exactly once in the same game',()=>{const c=core();let fired=0;c.app.audio.play('Yay!',()=>fired++);c.app.audio.play('Repeat');assert.equal(fired,1);c.advance(11000);assert.equal(fired,1);c.app.audio.play('Well done',()=>fired++);c.app.setSettings({sound:false});c.advance(11000);assert.equal(fired,2);});
test('a timer scheduled by praise is cancelled on navigation',()=>{const c=core();let fired=0;c.app.audio.play('Yay!',()=>c.app.session.timeout(()=>fired++,500));c.voices[0].onended();c.app.session.clear();c.advance(1000);assert.equal(fired,0);});
test('profiles remain bounded and personal prompts have a safe generic equivalent',()=>{const {app}=core();assert.equal(app.profile('<img src=x>'),null);assert.equal(app.profile('a'.repeat(25)),null);assert.equal(app.profile('  Avalynn  ').first,'Avalynn');assert.equal(app.arcadePhrase('Pop the balloons, Emma!','Emma'),'Pop the balloons!');assert.equal(app.arcadePhrase('Pop the balloons, Avalynn!','Avalynn'),'Pop the balloons, Avalynn!');});
test('catalog art and new narration exist',()=>{const context={window:{}};vm.createContext(context);vm.runInContext(read('catalog.js'),context);vm.runInContext(read('houses.js'),context);assert.equal(Object.keys(context.window.PLAYBOX_CATALOG).length,24);for(const entry of Object.values(context.window.PLAYBOX_CATALOG))assert.ok(fs.existsSync(path.join(root,'img',entry[3])),entry[3]);const {app}=core();for(const line of context.window.PLAYBOX_HOUSE_LINES){const f=path.join(root,'voice',app.slug(line)+'.mp3');assert.ok(fs.existsSync(f),f);assert.ok(fs.statSync(f).size>0,f);}});
test('drag ignores other fingers and cancellation restores the source',()=>{
  const s=read('index.html'), start=s.indexOf('  let _dragging=false;'),end=s.indexOf('  // ---------- MODE: 拔萝卜',start),events={};let drops=0;const source={style:{}},ghost={style:{},remove(){}};
  const context={window:{addEventListener:(name,fn)=>events[name]=fn,removeEventListener:name=>delete events[name]},document:{createElement:()=>ghost,body:{appendChild(){}}}};vm.createContext(context);vm.runInContext(s.slice(start,end)+';this.start=startDrag;',context);
  context.start(source,0,0,'',60,7,()=>drops++);events.pointerup({pointerId:8});assert.equal(drops,0);assert.equal(source.style.visibility,'hidden');events.pointercancel({pointerId:7});assert.equal(source.style.visibility,'');assert.equal(Object.keys(events).length,0);context.start(source,0,0,'',60,7,()=>drops++);assert.equal(source.style.visibility,'hidden');context.window.cancelPlayboxDrag();assert.equal(source.style.visibility,'');
});
test('HTTP errors never replace cached content and byte ranges work',async()=>{
  const events={},writes=[];const ctx={URL,Response,Headers,AbortController,setTimeout,clearTimeout,self:{location:{href:'https://example.test/app/sw.js'},addEventListener:(n,f)=>events[n]=f},caches:{open:async()=>({match:async()=>new Response('working'),put:async(...args)=>writes.push(args)})},fetch:async()=>new Response('failed',{status:503})};vm.createContext(ctx);vm.runInContext(read('sw.js'),ctx);let response;events.fetch({request:{url:'https://example.test/app/index.html',method:'GET',mode:'navigate',headers:new Headers()},respondWith:p=>response=p,waitUntil(){}});assert.equal(await(await response).text(),'working');assert.equal(writes.length,0);const range=await ctx.rangeResponse({headers:new Headers({Range:'bytes=2-4'})},new Response('abcdef'));assert.equal(range.status,206);assert.equal(await range.text(),'cde');
});
